### ISSUE TITLE
improve handling of ActionController::RoutingError type of errors

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal_web_ui#195]
Currently UI logs `ActionController::RoutingError` or `ActiveRecord::RecordNotFound` as a FATAL error with full trace stack for simple 404 Page Not Found type of errors.   These errors regularly spike up when external web scanners hit our site or when users access deleted ontology which can distort the health status of the application in NewRelic and can drown out more critical errors.   We should consider adjusting this behavior so that simple 404 types of access errors are not logged as FATAL errors.

```
F, [2022-05-19T14:02:40.514730 #25790] FATAL -- : [9b49f320-d088-4a5a-84e1-a5ed2f170878]
[9b49f320-d088-4a5a-84e1-a5ed2f170878] ActionController::RoutingError (No route matches [GET] "/apple-touch-icon.png"):
[9b49f320-d088-4a5a-84e1-a5ed2f170878]
[9b49f320-d088-4a5a-84e1-a5ed2f170878] actionpack (6.0.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] actionpack (6.0.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] railties (6.0.4.1) lib/rails/rack/logger.rb:37:in `call_app'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] railties (6.0.4.1) lib/rails/rack/logger.rb:26:in `block in call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] activesupport (6.0.4.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] activesupport (6.0.4.1) lib/active_support/tagged_logging.rb:28:in `tagged'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] activesupport (6.0.4.1) lib/active_support/tagged_logging.rb:80:in `tagged'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] railties (6.0.4.1) lib/rails/rack/logger.rb:26:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] actionpack (6.0.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] actionpack (6.0.4.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] activesupport (6.0.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] actionpack (6.0.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] actionpack (6.0.4.1) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] rack-mini-profiler (3.0.0) lib/mini_profiler/profiler.rb:249:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] railties (6.0.4.1) lib/rails/engine.rb:527:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] railties (6.0.4.1) lib/rails/railtie.rb:190:in `public_send'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] railties (6.0.4.1) lib/rails/railtie.rb:190:in `method_missing'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] newrelic_rpm (8.7.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] /usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
[9b49f320-d088-4a5a-84e1-a5ed2f170878] /usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

or 

```
E, [2022-05-18T03:54:55.778852 #14568] ERROR -- : [18394352-58bb-43dd-a900-b61a6147d501] No submissions for ontology: https://data.bioontology.org/ontologies/LOZANOAUGUSTO
F, [2022-05-18T03:56:48.187787 #14542] FATAL -- : [ec79cc60-00e8-4099-add1-bfee5656d542]
[ec79cc60-00e8-4099-add1-bfee5656d542] ActiveRecord::RecordNotFound (Not Found):
[ec79cc60-00e8-4099-add1-bfee5656d542]
[ec79cc60-00e8-4099-add1-bfee5656d542] app/controllers/application_controller.rb:91:in `not_found'
[ec79cc60-00e8-4099-add1-bfee5656d542] app/controllers/application_controller.rb:413:in `get_class'
[ec79cc60-00e8-4099-add1-bfee5656d542] app/controllers/ontologies_controller.rb:144:in `classes'
[ec79cc60-00e8-4099-add1-bfee5656d542] app/controllers/ontologies_controller.rb:301:in `show'
```

**Comment by alexskr** [comment]
**Escalating this — it's actively filling up production logs.**

**Impact.** Every 404 from bot traffic and vulnerability scanners writes a FATAL entry with a full backtrace, and a subset of them (any URL ending in an extension Rails recognizes, e.g. `.png`) additionally trips a failsafe crash inside the error handler that dumps the entire template-resolution search path. The volume is continuous and entirely noise — it scales with scanner and bot traffic, not with real usage. The real cost isn't disk, it's signal: genuine FATAL errors are drowned out, and NewRelic's error rate is distorted to the point where the app's health status isn't trustworthy.

**Two problems on the same requests:**

1. *The 404 handler itself crashes.* `config.exceptions_app = self.routes` re-dispatches to `errors#not_found` with the original request format attached, so `/apple-touch-icon.png` (the example in the original report) looks for `errors/not_found.png` and raises inside the exception handler:
   ```
   Error during failsafe response: Missing template errors/not_found, application/not_found
   with {:locale=>[:en], :formats=>[:png], ...}
   ```

2. *Routine 404s are logged as FATAL with full stack traces* — the original complaint here, and the bulk of the volume. There is no `rescue_from` and no `config.action_dispatch.rescue_responses` tuning anywhere in the app today.

**Ask:** prioritize (2) in the current cycle. It's a bounded change — configure `rescue_responses`/log level so `ActionController::RoutingError` and `ActiveRecord::RecordNotFound` log at `info` without a backtrace, and keep FATAL for actual failures. Item (1) alone stops the failsafe dumps but leaves a FATAL + backtrace per scanner hit.

---

**Related issues** (this ticket is the umbrella for the log-noise problem):

*Same failure path:*
- ncbo/bioportal_web_ui#160 — bogus `.xml`/`.json`/`.jpg` requests return 500/406 instead of 404. Same root cause as item (1); fix in flight. Should close when it lands.
- ncbo/bioportal_web_ui#153 — any URL ending in `.<anything>` returns a valid page. The route format constraints proposed there are the correct long-term fix, **but must land after #160** — constraining formats converts every `.php`/`.png` probe into a routing 404, i.e. straight into the crashing handler.
- ncbo/bioportal_web_ui#208 and ncbo/bioportal_web_ui#369 — `NoMethodError (undefined method 'notes' for nil:NilClass)`. Shared root cause: `ApplicationController#not_found` renders and *returns* on XHR instead of halting, so callers keep executing with a nil `@concept` (see `app/controllers/ajax_proxy_controller.rb:28-31`, `app/controllers/application_controller.rb:100`). Each occurrence is another FATAL + backtrace in the logs. Neither ticket names this cause.

**Comment by jonquet** [comment]
Not sure about the details of the issue.. but I do agree our logging is generally too much verbose and does not resist "deny or service" atatcks... 
The problem is not only the fact taht we are verbose in the logs, .... even before AI bots, its been 10 years that we are regulary facing automatic bots trying to index our content and generating random URL starting with our portal domain... and all of them go to the app, go to the back end go to the database to simply answer "404" or alike...  it uses a huge set of resources... for heursitics that could be tested upfront with simple URL patterns in a proxy.
