### ISSUE TITLE
Attempting to add a proposal shows "content missing" error for anonymous users

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#350]
In the `master` branch (production environment):

If an **anonymous user** selects any menu item from the "Add a proposal" dropdown menu, they're redirected to the login page. To access this dropdown menu, navigate to the Classes -> Details tab for any ontology where change requests are enabled. For a list of ontologies where change requests are enabled, refer to the [change_request](https://github.com/ncbo/bioportal_web_ui/blob/156d1b83357a2c50b0fddea370d191f9b718f902/config/change_request.yml) YAML file.

 In the `sync-agroportal` branch:

If an **anonymous user** selects any menu item from the "Add a proposal" dropdown menu, the content in the right-hand side of the Classes pane is erased and a "Content missing" error is displayed. Stack trace from the developer console:

```
application-50c822a29973c026270b9576fc124e2a14567dcf313060c9ce0182ab607d44a1.js:22 Uncaught (in promise) hd: Unhandled Promise Rejection: The response (200) did not contain the expected <turbo-frame id="concept_show"> and will be ignored. To perform a full page visit instead, set turbo-visit-control to reload.
    at dd.throwFrameMissingError (https://stage.bioontology.org/assets/application-50c822a29973c026270b9576fc124e2a14567dcf313060c9ce0182ab607d44a1.js:22:9080)
    at dd.handleFrameMissingFromResponse (https://stage.bioontology.org/assets/application-50c822a29973c026270b9576fc124e2a14567dcf313060c9ce0182ab607d44a1.js:22:8820)
    at dd.loadFrameResponse (https://stage.bioontology.org/assets/application-50c822a29973c026270b9576fc124e2a14567dcf313060c9ce0182ab607d44a1.js:22:7123)
    at async dd.loadResponse (https://stage.bioontology.org/assets/application-50c822a29973c026270b9576fc124e2a14567dcf313060c9ce0182ab607d44a1.js:22:4366)
    at async dd.requestSucceededWithResponse (https://stage.bioontology.org/assets/application-50c822a29973c026270b9576fc124e2a14567dcf313060c9ce0182ab607d44a1.js:22:5520)
```

**Comment by jvendetti** [comment]
Screen recording that shows the behavior:

https://github.com/user-attachments/assets/01958806-fc8c-4f81-b436-0cd7ab5deddd
