### ISSUE TITLE
When adding an ontology that has a view to the "Custom Ontology Set", then the ontology is browsable anymore

### ISSUE THREAD

**Issue by jonquet** [ncbo/bioportal_web_ui#36]
How to reproduce: 
Log in with you user account.
Goes to "Custom Ontology Set" and add an ontology to your custom set that has a view in BioPortal e.g. MESH
Then go to browse (you will see only the set)
Click on the ontology in the set
=> Something went wrong.

@vemonet to complete with logs or other info we have observed locally.

**Comment by jvendetti** [comment]
This issue was recently [reported again](http://ncbo-support.2288202.n4.nabble.com/bioontology-support-BioPortal-Feedback-from-ORDO-Orphanet-tp4656499p4656517.html) on our support list by Marc Hanauer. I configured my BioPortal account to use a custom ontology set of ORDO and reproduced the error.

The UI stack trace is:

```
Started GET "/ontologies/ORDO" for ::1 at 2018-07-16 15:18:20 -0700
Processing by OntologiesController#show as HTML
  Parameters: {"id"=>"ORDO"}
Completed 500 Internal Server Error in 470ms (ActiveRecord: 0.0ms)

MultiJson::ParseError (Problem retrieving:
http://stagedata.bioontology.org/ontologies/ORDO/views?include=all

Error: Problem loading json
<h1>Internal Server Error</h1>
/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_api_ruby_client-efa823cdccaa/lib/ontologies_api_client/http.rb:276:in `rescue in load_json'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_api_ruby_client-efa823cdccaa/lib/ontologies_api_client/http.rb:273:in `load_json'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_api_ruby_client-efa823cdccaa/lib/ontologies_api_client/http.rb:145:in `object_from_json'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_api_ruby_client-efa823cdccaa/lib/ontologies_api_client/middleware/faraday-object-cache.rb:94:in `block in call'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.0/lib/faraday/response.rb:61:in `on_complete'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_api_ruby_client-efa823cdccaa/lib/ontologies_api_client/middleware/faraday-object-cache.rb:63:in `call'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_api_ruby_client-efa823cdccaa/lib/ontologies_api_client/middleware/faraday-last-updated.rb:16:in `call'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_api_ruby_client-efa823cdccaa/lib/ontologies_api_client/middleware/faraday-slices.rb:16:in `call'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_api_ruby_client-efa823cdccaa/lib/ontologies_api_client/middleware/faraday-user-apikey.rb:16:in `call'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.0/lib/faraday/rack_builder.rb:143:in `build_response'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.0/lib/faraday/connection.rb:387:in `run_request'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.0/lib/faraday/connection.rb:138:in `get'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_api_ruby_client-efa823cdccaa/lib/ontologies_api_client/http.rb:63:in `get'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_api_ruby_client-efa823cdccaa/lib/ontologies_api_client/link_explorer.rb:49:in `explore_link'
	/Users/jvendetti/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_api_ruby_client-efa823cdccaa/lib/ontologies_api_client/link_explorer.rb:16:in `method_missing'
	/Users/jvendetti/Development/GitHub/ncbo/bioportal_web_ui/app/controllers/ontologies_controller.rb:374:in `summary'
	/Users/jvendetti/Development/GitHub/ncbo/bioportal_web_ui/app/controllers/ontologies_controller.rb:350:in `show'
```

If you execute the specific REST call in a local dev environment that's mentioned in the UI stack trace from above (http://stagedata.bioontology.org/ontologies/ORDO/views?include=all), you get:

```
RuntimeError: can't modify frozen Array
	/Users/jvendetti/Development/GitHub/ncbo/ontologies_api/helpers/users_helper.rb:15:in `delete_if'
	/Users/jvendetti/Development/GitHub/ncbo/ontologies_api/helpers/users_helper.rb:15:in `filter_for_user_onts'
	/Users/jvendetti/Development/GitHub/ncbo/ontologies_api/helpers/application_helper.rb:130:in `reply'
	/Users/jvendetti/Development/GitHub/ncbo/ontologies_api/controllers/views_controller.rb:11:in `block (2 levels) in <class:ViewsController>'
```
