### ISSUE TITLE
Create new file upload submission without specifying file results in 500 error

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#71]
Steps to reproduce:

1. Navigate to any ontology summary page in BioPortal.
2. Click the Add submission link.
3. Fill out the required fields.
4. Select the "Upload Local File" radio button in the Location section of the form, but don't specify a file name with the Choose File button.
5. Click the Add submission button.

The UI then shows the "We're sorry but something has gone wrong" error message (a 500 error).

Stack trace from local development environment:

```
Completed 500 Internal Server Error in 5592ms (ActiveRecord: 0.0ms)

TypeError (no implicit conversion of Symbol into Integer):
  app/controllers/submissions_controller.rb:25:in `[]'
  app/controllers/submissions_controller.rb:25:in `create'
```

**Comment by jvendetti** [comment]
Fixed in commit https://github.com/ncbo/bioportal_web_ui/commit/e5a038326b19e5513c97b24f8a3893b8dec68992
